EXCEL_FILE = r'OG in progress.xlsx'
SHEET_NAME = 'Sheet1'
PAPERS_FOLDER = 'papers'
STATUS_FOLDER = 'status'
PICKLES_FOLDER = 'pickles'
XML_FOLDER = 'xml'
PROJECT_PATH = 'C:/Users/Bar Ifrah/Documents/second_degree/OCRtoGazzeteExtractPicturesAndText'
PATH_WKTHMLTOIMAGE = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe'
IMAGE_OPTIONS = {'format': 'png', 'width': '250'}
